-- TelcoRec schema for H2 embedded database
-- All tables use CREATE TABLE IF NOT EXISTS for idempotent execution

-- Service plans / commercial offers
CREATE TABLE IF NOT EXISTS SERVICE_PLANS (
    ID                       BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PLAN_CODE                VARCHAR(30)  NOT NULL,
    PLAN_NAME                VARCHAR(120),
    MONTHLY_FEE              DECIMAL(10,2),
    INCLUDED_VOICE_MINUTES   INTEGER,
    INCLUDED_SMS_COUNT       INTEGER,
    INCLUDED_DATA_MB         BIGINT,
    EXTRA_DATA_COST_PER_MB   DECIMAL(10,4),
    EXTRA_VOICE_COST_PER_MIN DECIMAL(10,4),
    ROAMING_ENABLED          BOOLEAN,
    DESCRIPTION              VARCHAR(500),
    CONSTRAINT UQ_SP_CODE UNIQUE (PLAN_CODE)
);

-- Subscriber accounts
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID                  BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID         VARCHAR(20) NOT NULL,
    FULL_NAME           VARCHAR(120),
    EMAIL               VARCHAR(120),
    PHONE_NUMBER        VARCHAR(20),
    ADDRESS             VARCHAR(200),
    CITY                VARCHAR(60),
    COUNTRY             VARCHAR(60) DEFAULT 'Italy',
    STATUS              VARCHAR(20),
    SERVICE_PLAN        VARCHAR(30),
    CONTRACT_START_DATE DATE,
    CONSTRAINT UQ_CUST_ID UNIQUE (CUSTOMER_ID),
    CONSTRAINT FK_CUST_PLAN FOREIGN KEY (SERVICE_PLAN) REFERENCES SERVICE_PLANS(PLAN_CODE)
);

CREATE INDEX IF NOT EXISTS IDX_CUST_STATUS ON CUSTOMERS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_CUST_PLAN   ON CUSTOMERS(SERVICE_PLAN);

-- Monthly invoices
CREATE TABLE IF NOT EXISTS INVOICES (
    ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    INVOICE_NUMBER        VARCHAR(30) NOT NULL,
    CUSTOMER_ID_FK        BIGINT      NOT NULL,
    BILLING_PERIOD_START  DATE,
    BILLING_PERIOD_END    DATE,
    ISSUE_DATE            DATE,
    DUE_DATE              DATE,
    TOTAL_AMOUNT          DECIMAL(10,2),
    STATUS                VARCHAR(20),
    RECONCILIATION_STATUS VARCHAR(30) DEFAULT 'UNPROCESSED',
    NOTES                 VARCHAR(1000),
    CONSTRAINT UQ_INV_NUM UNIQUE (INVOICE_NUMBER),
    CONSTRAINT FK_INV_CUST FOREIGN KEY (CUSTOMER_ID_FK) REFERENCES CUSTOMERS(ID)
);

CREATE INDEX IF NOT EXISTS IDX_INV_CUST       ON INVOICES(CUSTOMER_ID_FK);
CREATE INDEX IF NOT EXISTS IDX_INV_REC_STATUS ON INVOICES(RECONCILIATION_STATUS);
CREATE INDEX IF NOT EXISTS IDX_INV_PERIOD     ON INVOICES(BILLING_PERIOD_START, BILLING_PERIOD_END);

-- Individual charge lines
CREATE TABLE IF NOT EXISTS INVOICE_ITEMS (
    ID                BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    INVOICE_ID_FK     BIGINT       NOT NULL,
    ITEM_TYPE         VARCHAR(30),
    DESCRIPTION       VARCHAR(300),
    QUANTITY          DECIMAL(12,4),
    UNIT_PRICE        DECIMAL(10,4),
    TOTAL_PRICE       DECIMAL(10,2),
    SERVICE_START_DATE DATE,
    SERVICE_END_DATE   DATE,
    CONSTRAINT FK_ITEM_INV FOREIGN KEY (INVOICE_ID_FK) REFERENCES INVOICES(ID)
);

CREATE INDEX IF NOT EXISTS IDX_ITEM_INV ON INVOICE_ITEMS(INVOICE_ID_FK);

-- Network CDR usage records
CREATE TABLE IF NOT EXISTS CONSUMPTION_RECORDS (
    ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID           VARCHAR(20) NOT NULL,
    BILLING_PERIOD_START  DATE,
    BILLING_PERIOD_END    DATE,
    ACTUAL_VOICE_MINUTES  INTEGER,
    ACTUAL_SMS_COUNT      INTEGER,
    ACTUAL_DATA_MB        BIGINT,
    ROAMING_VOICE_MINUTES INTEGER,
    ROAMING_DATA_MB       BIGINT,
    PREMIUM_SMS_COUNT     INTEGER,
    RECORDED_AT           TIMESTAMP,
    SOURCE                VARCHAR(30)
);

CREATE INDEX IF NOT EXISTS IDX_CDR_CUST   ON CONSUMPTION_RECORDS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_CDR_PERIOD ON CONSUMPTION_RECORDS(BILLING_PERIOD_START, BILLING_PERIOD_END);

-- Reconciliation outcomes
CREATE TABLE IF NOT EXISTS RECONCILIATION_RESULTS (
    ID                      BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    INVOICE_ID_FK           BIGINT      NOT NULL,
    CONSUMPTION_RECORD_ID_FK BIGINT,
    PROCESSED_AT            TIMESTAMP,
    STATUS                  VARCHAR(30),
    INVOICED_AMOUNT         DECIMAL(10,2),
    EXPECTED_AMOUNT         DECIMAL(10,2),
    DISCREPANCY_AMOUNT      DECIMAL(10,2),
    DISCREPANCY_DETAILS     VARCHAR(2000),
    RESOLVED_AT             TIMESTAMP,
    RESOLVED_BY             VARCHAR(80),
    CONSTRAINT FK_REC_INV FOREIGN KEY (INVOICE_ID_FK)            REFERENCES INVOICES(ID),
    CONSTRAINT FK_REC_CDR FOREIGN KEY (CONSUMPTION_RECORD_ID_FK) REFERENCES CONSUMPTION_RECORDS(ID)
);

CREATE INDEX IF NOT EXISTS IDX_REC_STATUS ON RECONCILIATION_RESULTS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_REC_INV    ON RECONCILIATION_RESULTS(INVOICE_ID_FK);
